version: '3.1'
services:
  api:
    build: api
    container_name: api
    depends_on:
      - ITRUM-TestApi-DB
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ITRUM-TestApi-DB:45533/ITRUM-TestApi

  ITRUM-TestApi-DB:
    image: postgres:14-alpine
    container_name: ITRUM-TestApi-DB
    ports:
      - "45533:45533"
    environment:
      - POSTGRES_DB=ITRUM-TestApi
      - POSTGRES_USER=ITRUM-TestApi
      - POSTGRES_PASSWORD=ITRUM-TestApi