version: '3.1'
services:
  api:
    build: api
    container_name: api
    depends_on:
      - ITRUM-TestApi-DB
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ITRUM-TestApi-DB:5432/ITRUM-TestApi

  ITRUM-TestApi-DB:
    image: postgres:14-alpine
    container_name: ITRUM-TestApi-DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ITRUM-TestApi
      - POSTGRES_USER=ITRUM-TestApi
      - POSTGRES_PASSWORD=ITRUM-TestApi